using Cheetah.Matches.Relay.Codec;
using Cheetah.Matches.Relay.Codec.Formatter;
using Cheetah.Matches.Relay.Types;
using UnityEngine;
using Cheetah.Matches.Relay.Tests.Runtime.Codec.Field;

// ReSharper disable once CheckNamespace
namespace Cheetah.Matches.Relay.Tests.Runtime.Codec.Field
{
		// warning warning warning warning warning
		// Code generated by Cheetah relay codec generator - DO NOT EDIT
		// warning warning warning warning warning
		public class TestCodecArrayFieldInnerCodec:Codec<Cheetah.Matches.Relay.Tests.Runtime.Codec.Field.TestCodecArrayField.Inner>
		{
			public void Decode(ref CheetahBuffer buffer, ref Cheetah.Matches.Relay.Tests.Runtime.Codec.Field.TestCodecArrayField.Inner dest)
			{
				dest.value = IntFormatter.Instance.Read(ref buffer);
			}
	
			public void  Encode(ref Cheetah.Matches.Relay.Tests.Runtime.Codec.Field.TestCodecArrayField.Inner source, ref CheetahBuffer buffer)
			{
				IntFormatter.Instance.Write(source.value,ref buffer);
			}
	
	
			[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]
			private static void OnRuntimeMethodLoad()
			{
				CodecRegistryBuilder.RegisterDefault(factory=>new TestCodecArrayFieldInnerCodec());
			}
	
		}
	
	
}
