[package]
name = "cheetah-matches-realtime-server-plugin"
version = "0.0.1"
authors = ["kviring <alex@kviring.com>"]
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "lib"]

[dependencies]
lazy_static = "1.4.0"
tonic = "0.8.2"
prost = "0.11.0"
fnv = "1.0.7"
tokio = { version = "1.21.2", features = ["rt-multi-thread"] }
crossbeam = "0.8.2"
thiserror = "1.0.37"
widestring = "1.0.2"
anyhow = "1.0.66"

[dev-dependencies]
futures = "0.3.25"
async-stream = "0.3"
tower = "0.4.13"
tokio-stream = "0.1.11"
mockall = "0.11.3"


[build-dependencies]
tonic-build = { version = "0.8.2" }
