[package]
name = "cheetah-matches-stub-matchmaking"
version = "999.999.999"
edition = "2021"

[[bin]]
name = "cheetah-matches-stubmatchmaking-server"
path = "src/bin/service.rs"

[dependencies]
tokio = { version = "1.16.1", features = ["rt-multi-thread", "time", "fs", "macros", "net"] }
tonic = "0.6.2"
prost = "0.9.0"
cheetah-libraries-microservice = { path = "../../../libraries/rust/Microservice/" }
async-recursion = "1.0.0"
tokio-stream = { version = "0.1.8", features = ["net"] }
tonic-web = "0.2.0"
tracing = "0.1.31"
uuid = { version = "1.0.0", features = ["v4", "serde"] }
jwt-tonic-user-uuid = "0.0.1"

[build-dependencies]
tonic-build = "0.6.2"
