replicaCount: 1
cpu:
  request: "0.1"
  limit: "1"
memory:
  request: 20Mi
  limit: 40Mi
redis:
  master:
    podAnnotations:
      linkerd.io/inject: enabled
    persistence:
      enabled: false
      size: 1Gi
  architecture: standalone
  fullnameOverride: cheetah-user-accounts-redis
  auth:
    existingSecret: cheetah-user-accounts-redis-password
    existingSecretPasswordKey: password
  cluster:
    enabled: false
  volumePermissions:
    enabled: true
  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001

internalPostgresql:
  enable: true
  persistence:
    enabled: false
env:
  - name: "POSTGRES_PORT"
    value: "5432"
  - name: "POSTGRES_DB"
    valueFrom:
      secretKeyRef:
        name: cheetah-user-accounts-postgresql
        key: user
  - name: "POSTGRES_HOST"
    value: "cheetah-user-accounts-postgresql"
  - name: "POSTGRES_USER"
    valueFrom:
      secretKeyRef:
        name: cheetah-user-accounts-postgresql
        key: user
  - name: "POSTGRES_PASSWORD"
    valueFrom:
      secretKeyRef:
        name: cheetah-user-accounts-postgresql
        key: password
  - name: "REDIS_HOST"
    value: "cheetah-user-accounts-redis-master"
  - name: "REDIS_PORT"
    value: "6379"
  - name: "REDIS_AUTH"
    valueFrom:
      secretKeyRef:
        name: cheetah-user-accounts-redis-password
        key: password