apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  template:
    spec:
      ports:
        - name: default
          containerPort: 5555
      template:
        metadata:
          labels:
            prometheus: "true"
          annotations:
            linkerd.io/inject: enabled
        spec:
          {{- with .Values.tolerations }}
          tolerations:
              {{- toYaml . | nindent 11 }}
          {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
               {{- toYaml . | nindent 11 }}
          {{- end }}
          containers:
            - name: relay
              image: "ghcr.io/cheetah-game-platform/platform/cheetah-matches-realtime:{{ .Values.global.platformImageVersion }}"
              imagePullPolicy: Always
              securityContext:
                readOnlyRootFilesystem: true
              startupProbe:
                exec:
                  command: [ "/bin/grpc_health_probe", "-addr=:5001", "-addr=:5002" ]
                initialDelaySeconds: 5
              livenessProbe:
                exec:
                  command: [ "/bin/grpc_health_probe", "-addr=:5001","-addr=:5002" ]
                initialDelaySeconds: 10
              resources:
                limits:
                  cpu: {{ .Values.cpu.limit }}
                  memory: {{ .Values.memory.limit }}
                requests:
                  cpu: {{ .Values.cpu.request }}
                  memory: {{ .Values.memory.request }}
              env:
                - name: ENABLE_AGONES
                  value: "true"
                # используется для публикации адреса relay в registry
                - name: POD_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.podIP
                - name: CHEETAH_MATCHES_REGISTRY_INTERNAL_SERVICE_HOST
                  value: "$(CHEETAH_MATCHES_REGISTRY_INTERNAL_SERVICE_HOST)"
                - name: CHEETAH_MATCHES_REGISTRY_INTERNAL_SERVICE_PORT
                  value: "$(CHEETAH_MATCHES_REGISTRY_INTERNAL_SERVICE_PORT)"
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: LOKI_URL
                  value: {{.Values.global.lokiUrl}}
              ports:
                - name: prometheus
                  containerPort: 3000
                  protocol: TCP

