version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: dependabot
  - package-ecosystem: "cargo"
    directory: "/modules/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"