using Games.Cheetah.Client.Codec;
using Games.Cheetah.Client.Codec.Formatter;
using Games.Cheetah.Client.Types;
using UnityEngine;
using Games.Cheetah.Client.Tests.Codec.Field;

// ReSharper disable once CheckNamespace
namespace Games_Cheetah_Client_Tests_Codec_Field
{
		// warning warning warning warning warning
		// Code generated by Cheetah relay codec generator - DO NOT EDIT
		// warning warning warning warning warning
		public class TestEnumFieldStructureCodec:Codec<Games.Cheetah.Client.Tests.Codec.Field.TestEnumField.Structure>
		{
			public void Decode(ref CheetahBuffer buffer, ref Games.Cheetah.Client.Tests.Codec.Field.TestEnumField.Structure dest)
			{
				dest.enumValue = (Games.Cheetah.Client.Tests.Codec.Field.TestEnumField.EnumTest)ByteFormatter.Instance.Read(ref buffer);
			}
	
			public void  Encode(in Games.Cheetah.Client.Tests.Codec.Field.TestEnumField.Structure source, ref CheetahBuffer buffer)
			{
				ByteFormatter.Instance.Write((byte)source.enumValue,ref buffer);
			}
	
	
			[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]
			private static void OnRuntimeMethodLoad()
			{
				CodecRegistryBuilder.RegisterDefault(factory=>new TestEnumFieldStructureCodec());
			}
	
		}
	
	
}
