using Games.Cheetah.Client.Codec;
using Games.Cheetah.Client.Codec.Formatter;
using Games.Cheetah.Client.Types;
using Games.Cheetah.Client.Types.Field;
using UnityEngine;
using Games.Cheetah.Client.Tests.Server.Types;

// ReSharper disable once CheckNamespace
namespace Games_Cheetah_Client_Tests_Server_Types
{
		// warning warning warning warning warning
		// Code generated by Cheetah relay codec generator - DO NOT EDIT
		// warning warning warning warning warning
		public class DropMineEventCodec:Codec<Games.Cheetah.Client.Tests.Server.Types.DropMineEvent>
		{
			public void Decode(ref NetworkBuffer buffer, ref Games.Cheetah.Client.Tests.Server.Types.DropMineEvent dest)
			{
				dest.MineId = IntFormatter.Instance.Read(ref buffer);
			}
	
			public void  Encode(in Games.Cheetah.Client.Tests.Server.Types.DropMineEvent source, ref NetworkBuffer buffer)
			{
				IntFormatter.Instance.Write(source.MineId,ref buffer);
			}
	
	
			[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]
			private static void OnRuntimeMethodLoad()
			{
				CodecRegistryBuilder.RegisterDefault(factory=>new DropMineEventCodec());
			}
	
		}
	
	
}
