[package]
name = "cheetah-matches-realtime-client"
authors.workspace = true
edition.workspace = true
version = "0.0.1"


[lib]
crate-type = ["staticlib", "cdylib", "lib"]

[dependencies]
lazy_static.workspace = true
cheetah-matches-realtime-common = { path = "../../../common/Common" }
widestring.workspace = true
fnv.workspace = true
heapless = { workspace = true, features = ["serde"] }
thiserror.workspace = true
tracing.workspace = true
tracing-core.workspace = true
tracing-log.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
cheetah-matches-realtime = { path = "../../../server" }
easybench = "1.0.0"
rand.workspace = true
