using Cheetah.Matches.Relay.Codec;
using Cheetah.Matches.Relay.Codec.Formatter;
using Cheetah.Matches.Relay.Types;
using UnityEngine;
using Shared.Types;

// ReSharper disable once CheckNamespace
namespace Shared.Types
{
		// warning warning warning warning warning
		// Code generated by Cheetah relay codec generator - DO NOT EDIT
		// warning warning warning warning warning
		public class DropMineEventCodec:Codec<DropMineEvent>
		{
			public void Decode(ref CheetahBuffer buffer, ref DropMineEvent dest)
			{
				dest.MineId = PrimitiveReaders.ReadInt(ref buffer);
			}
	
			public void  Encode(ref DropMineEvent source, ref CheetahBuffer buffer)
			{
				PrimitiveWriters.Write(source.MineId,ref buffer);
			}
	
	
			[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]
			private static void OnRuntimeMethodLoad()
			{
				CodecRegistryBuilder.RegisterDefault(factory=>new DropMineEventCodec());
			}
	
		}
	
	
}
