apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: 1
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        prometheus: "true"
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "ghcr.io/cheetah-game-platform/platform/{{ .Chart.Name }}:{{ .Chart.Version }}"
          imagePullPolicy: Always
          securityContext:
            readOnlyRootFilesystem: true
          startupProbe:
            exec:
              command: [ "/bin/grpc_health_probe", "-addr=:5000" ]
            initialDelaySeconds: 5
          livenessProbe:
            exec:
              command: [ "/bin/grpc_health_probe", "-addr=:5000" ]
            initialDelaySeconds: 10
          resources:
            limits:
              cpu: {{ .Values.cpu.limit }}
              memory: 40Mi
            requests:
              cpu: {{ .Values.cpu.request }}
              memory: 20Mi
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOKI_URL
              value: {{.Values.global.lokiUrl}}
          ports:
            - name: prometheus
              containerPort: 3000
              protocol: TCP
