[package]
name = "cheetah-matches-realtime-embedded"
version = "0.1.0"
authors = ["kviring <alex@kviring.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cheetah-matches-realtime-common = { path = "../common/Common" }
cheetah-matches-realtime = { path = "../server" }
tokio = { version = "1.16.1", features = ["rt-multi-thread", "time", "fs", "macros", "net", "sync"] }
anyhow = "1.0.64"
thiserror = "1.0.34"
lazy_static = "1.4.0"
port_scanner = "0.1.5"

[build-dependencies]
tonic-build = { version = "0.6.2", features = ["rustfmt"] }
