[package]
name = "cheetah-matches-realtime-macro"
version = "0.1.0"
authors = ["Kviring Aleksey <alex@kviring.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0.103"
quote = "1.0.15"
proc-macro2 = "1.0.36"
Inflector = "0.11.4"

[lib]
proc-macro = true