// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cookie.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Games.Cheetah.Auth.External.Cookie {
  public static partial class Cookie
  {
    static readonly string __ServiceName = "games.cheetah.auth.external.cookie.Cookie";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Games.Cheetah.Auth.External.Cookie.RegistryRequest> __Marshaller_games_cheetah_auth_external_cookie_RegistryRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Games.Cheetah.Auth.External.Cookie.RegistryRequest.Parser));
    static readonly grpc::Marshaller<global::Games.Cheetah.Auth.External.Cookie.RegistryResponse> __Marshaller_games_cheetah_auth_external_cookie_RegistryResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Games.Cheetah.Auth.External.Cookie.RegistryResponse.Parser));
    static readonly grpc::Marshaller<global::Games.Cheetah.Auth.External.Cookie.LoginRequest> __Marshaller_games_cheetah_auth_external_cookie_LoginRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Games.Cheetah.Auth.External.Cookie.LoginRequest.Parser));
    static readonly grpc::Marshaller<global::Games.Cheetah.Auth.External.Cookie.LoginResponse> __Marshaller_games_cheetah_auth_external_cookie_LoginResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Games.Cheetah.Auth.External.Cookie.LoginResponse.Parser));

    static readonly grpc::Method<global::Games.Cheetah.Auth.External.Cookie.RegistryRequest, global::Games.Cheetah.Auth.External.Cookie.RegistryResponse> __Method_RegistryByCookie = new grpc::Method<global::Games.Cheetah.Auth.External.Cookie.RegistryRequest, global::Games.Cheetah.Auth.External.Cookie.RegistryResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RegistryByCookie",
        __Marshaller_games_cheetah_auth_external_cookie_RegistryRequest,
        __Marshaller_games_cheetah_auth_external_cookie_RegistryResponse);

    static readonly grpc::Method<global::Games.Cheetah.Auth.External.Cookie.LoginRequest, global::Games.Cheetah.Auth.External.Cookie.LoginResponse> __Method_LoginByCookie = new grpc::Method<global::Games.Cheetah.Auth.External.Cookie.LoginRequest, global::Games.Cheetah.Auth.External.Cookie.LoginResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "LoginByCookie",
        __Marshaller_games_cheetah_auth_external_cookie_LoginRequest,
        __Marshaller_games_cheetah_auth_external_cookie_LoginResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Games.Cheetah.Auth.External.Cookie.CookieReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Cookie</summary>
    [grpc::BindServiceMethod(typeof(Cookie), "BindService")]
    public abstract partial class CookieBase
    {
      /// <summary>
      ///
      ///Регистрация пользователя по cookie
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Games.Cheetah.Auth.External.Cookie.RegistryResponse> RegistryByCookie(global::Games.Cheetah.Auth.External.Cookie.RegistryRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///
      ///Вход пользователя по cookie
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Games.Cheetah.Auth.External.Cookie.LoginResponse> LoginByCookie(global::Games.Cheetah.Auth.External.Cookie.LoginRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Cookie</summary>
    public partial class CookieClient : grpc::ClientBase<CookieClient>
    {
      /// <summary>Creates a new client for Cookie</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public CookieClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Cookie that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public CookieClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected CookieClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected CookieClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      ///
      ///Регистрация пользователя по cookie
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Games.Cheetah.Auth.External.Cookie.RegistryResponse RegistryByCookie(global::Games.Cheetah.Auth.External.Cookie.RegistryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RegistryByCookie(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///
      ///Регистрация пользователя по cookie
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Games.Cheetah.Auth.External.Cookie.RegistryResponse RegistryByCookie(global::Games.Cheetah.Auth.External.Cookie.RegistryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RegistryByCookie, null, options, request);
      }
      /// <summary>
      ///
      ///Регистрация пользователя по cookie
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Games.Cheetah.Auth.External.Cookie.RegistryResponse> RegistryByCookieAsync(global::Games.Cheetah.Auth.External.Cookie.RegistryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RegistryByCookieAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///
      ///Регистрация пользователя по cookie
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Games.Cheetah.Auth.External.Cookie.RegistryResponse> RegistryByCookieAsync(global::Games.Cheetah.Auth.External.Cookie.RegistryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RegistryByCookie, null, options, request);
      }
      /// <summary>
      ///
      ///Вход пользователя по cookie
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Games.Cheetah.Auth.External.Cookie.LoginResponse LoginByCookie(global::Games.Cheetah.Auth.External.Cookie.LoginRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return LoginByCookie(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///
      ///Вход пользователя по cookie
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Games.Cheetah.Auth.External.Cookie.LoginResponse LoginByCookie(global::Games.Cheetah.Auth.External.Cookie.LoginRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_LoginByCookie, null, options, request);
      }
      /// <summary>
      ///
      ///Вход пользователя по cookie
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Games.Cheetah.Auth.External.Cookie.LoginResponse> LoginByCookieAsync(global::Games.Cheetah.Auth.External.Cookie.LoginRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return LoginByCookieAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///
      ///Вход пользователя по cookie
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Games.Cheetah.Auth.External.Cookie.LoginResponse> LoginByCookieAsync(global::Games.Cheetah.Auth.External.Cookie.LoginRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_LoginByCookie, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override CookieClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new CookieClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(CookieBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_RegistryByCookie, serviceImpl.RegistryByCookie)
          .AddMethod(__Method_LoginByCookie, serviceImpl.LoginByCookie).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, CookieBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_RegistryByCookie, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Games.Cheetah.Auth.External.Cookie.RegistryRequest, global::Games.Cheetah.Auth.External.Cookie.RegistryResponse>(serviceImpl.RegistryByCookie));
      serviceBinder.AddMethod(__Method_LoginByCookie, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Games.Cheetah.Auth.External.Cookie.LoginRequest, global::Games.Cheetah.Auth.External.Cookie.LoginResponse>(serviceImpl.LoginByCookie));
    }

  }
}
#endregion
