// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: matches.factory.admin.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Cheetah.Matches.Factory.Editor.GRPC {
  /// <summary>
  ///*
  ///Общие команды для получения информации и управления сервером
  /// </summary>
  public static partial class Configurations
  {
    static readonly string __ServiceName = "cheetah.matches.factory.admin.Configurations";

    static readonly grpc::Marshaller<global::Cheetah.Matches.Factory.Editor.GRPC.GetItemsNamesRequest> __Marshaller_cheetah_matches_factory_admin_GetItemsNamesRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Cheetah.Matches.Factory.Editor.GRPC.GetItemsNamesRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Cheetah.Matches.Factory.Editor.GRPC.GetItemsNamesResponse> __Marshaller_cheetah_matches_factory_admin_GetItemsNamesResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Cheetah.Matches.Factory.Editor.GRPC.GetItemsNamesResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Cheetah.Matches.Factory.Editor.GRPC.GetItemsNamesRequest, global::Cheetah.Matches.Factory.Editor.GRPC.GetItemsNamesResponse> __Method_GetItemNames = new grpc::Method<global::Cheetah.Matches.Factory.Editor.GRPC.GetItemsNamesRequest, global::Cheetah.Matches.Factory.Editor.GRPC.GetItemsNamesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetItemNames",
        __Marshaller_cheetah_matches_factory_admin_GetItemsNamesRequest,
        __Marshaller_cheetah_matches_factory_admin_GetItemsNamesResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Cheetah.Matches.Factory.Editor.GRPC.MatchesFactoryAdminReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Configurations</summary>
    [grpc::BindServiceMethod(typeof(Configurations), "BindService")]
    public abstract partial class ConfigurationsBase
    {
      /// <summary>
      ///*
      ///Получить имена полей и шаблонов
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Cheetah.Matches.Factory.Editor.GRPC.GetItemsNamesResponse> GetItemNames(global::Cheetah.Matches.Factory.Editor.GRPC.GetItemsNamesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Configurations</summary>
    public partial class ConfigurationsClient : grpc::ClientBase<ConfigurationsClient>
    {
      /// <summary>Creates a new client for Configurations</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ConfigurationsClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Configurations that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ConfigurationsClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ConfigurationsClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ConfigurationsClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      ///*
      ///Получить имена полей и шаблонов
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Cheetah.Matches.Factory.Editor.GRPC.GetItemsNamesResponse GetItemNames(global::Cheetah.Matches.Factory.Editor.GRPC.GetItemsNamesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetItemNames(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///*
      ///Получить имена полей и шаблонов
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Cheetah.Matches.Factory.Editor.GRPC.GetItemsNamesResponse GetItemNames(global::Cheetah.Matches.Factory.Editor.GRPC.GetItemsNamesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetItemNames, null, options, request);
      }
      /// <summary>
      ///*
      ///Получить имена полей и шаблонов
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Cheetah.Matches.Factory.Editor.GRPC.GetItemsNamesResponse> GetItemNamesAsync(global::Cheetah.Matches.Factory.Editor.GRPC.GetItemsNamesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetItemNamesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///*
      ///Получить имена полей и шаблонов
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Cheetah.Matches.Factory.Editor.GRPC.GetItemsNamesResponse> GetItemNamesAsync(global::Cheetah.Matches.Factory.Editor.GRPC.GetItemsNamesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetItemNames, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ConfigurationsClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ConfigurationsClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ConfigurationsBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetItemNames, serviceImpl.GetItemNames).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ConfigurationsBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetItemNames, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Cheetah.Matches.Factory.Editor.GRPC.GetItemsNamesRequest, global::Cheetah.Matches.Factory.Editor.GRPC.GetItemsNamesResponse>(serviceImpl.GetItemNames));
    }

  }
}
#endregion
