// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: service.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Games.Cheetah.Realtime.GRPC {
  public static partial class RealtimeServerManagementService
  {
    static readonly string __ServiceName = "cheetah.matches.realtime.grpc.RealtimeServerManagementService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Games.Cheetah.Realtime.GRPC.RoomTemplate> __Marshaller_cheetah_matches_realtime_grpc_RoomTemplate = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Games.Cheetah.Realtime.GRPC.RoomTemplate.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Games.Cheetah.Realtime.GRPC.RoomIdResponse> __Marshaller_cheetah_matches_realtime_grpc_RoomIdResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Games.Cheetah.Realtime.GRPC.RoomIdResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Games.Cheetah.Realtime.GRPC.CreateMemberRequest> __Marshaller_cheetah_matches_realtime_grpc_CreateMemberRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Games.Cheetah.Realtime.GRPC.CreateMemberRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Games.Cheetah.Realtime.GRPC.CreateMemberResponse> __Marshaller_cheetah_matches_realtime_grpc_CreateMemberResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Games.Cheetah.Realtime.GRPC.CreateMemberResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Games.Cheetah.Realtime.GRPC.DeleteMemberRequest> __Marshaller_cheetah_matches_realtime_grpc_DeleteMemberRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Games.Cheetah.Realtime.GRPC.DeleteMemberRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Games.Cheetah.Realtime.GRPC.DeleteMemberResponse> __Marshaller_cheetah_matches_realtime_grpc_DeleteMemberResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Games.Cheetah.Realtime.GRPC.DeleteMemberResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Games.Cheetah.Realtime.GRPC.CreateSuperMemberRequest> __Marshaller_cheetah_matches_realtime_grpc_CreateSuperMemberRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Games.Cheetah.Realtime.GRPC.CreateSuperMemberRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Games.Cheetah.Realtime.GRPC.ProbeRequest> __Marshaller_cheetah_matches_realtime_grpc_ProbeRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Games.Cheetah.Realtime.GRPC.ProbeRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Games.Cheetah.Realtime.GRPC.ProbeResponse> __Marshaller_cheetah_matches_realtime_grpc_ProbeResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Games.Cheetah.Realtime.GRPC.ProbeResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Games.Cheetah.Realtime.GRPC.EmptyRequest> __Marshaller_cheetah_matches_realtime_grpc_EmptyRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Games.Cheetah.Realtime.GRPC.EmptyRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Games.Cheetah.Realtime.GRPC.GetRoomsResponse> __Marshaller_cheetah_matches_realtime_grpc_GetRoomsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Games.Cheetah.Realtime.GRPC.GetRoomsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Games.Cheetah.Realtime.GRPC.DeleteRoomRequest> __Marshaller_cheetah_matches_realtime_grpc_DeleteRoomRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Games.Cheetah.Realtime.GRPC.DeleteRoomRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Games.Cheetah.Realtime.GRPC.DeleteRoomResponse> __Marshaller_cheetah_matches_realtime_grpc_DeleteRoomResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Games.Cheetah.Realtime.GRPC.DeleteRoomResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Games.Cheetah.Realtime.GRPC.GetRoomsMembersCountResponse> __Marshaller_cheetah_matches_realtime_grpc_GetRoomsMembersCountResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Games.Cheetah.Realtime.GRPC.GetRoomsMembersCountResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Games.Cheetah.Realtime.GRPC.RoomTemplate, global::Games.Cheetah.Realtime.GRPC.RoomIdResponse> __Method_CreateRoom = new grpc::Method<global::Games.Cheetah.Realtime.GRPC.RoomTemplate, global::Games.Cheetah.Realtime.GRPC.RoomIdResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateRoom",
        __Marshaller_cheetah_matches_realtime_grpc_RoomTemplate,
        __Marshaller_cheetah_matches_realtime_grpc_RoomIdResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Games.Cheetah.Realtime.GRPC.CreateMemberRequest, global::Games.Cheetah.Realtime.GRPC.CreateMemberResponse> __Method_CreateMember = new grpc::Method<global::Games.Cheetah.Realtime.GRPC.CreateMemberRequest, global::Games.Cheetah.Realtime.GRPC.CreateMemberResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateMember",
        __Marshaller_cheetah_matches_realtime_grpc_CreateMemberRequest,
        __Marshaller_cheetah_matches_realtime_grpc_CreateMemberResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Games.Cheetah.Realtime.GRPC.DeleteMemberRequest, global::Games.Cheetah.Realtime.GRPC.DeleteMemberResponse> __Method_DeleteMember = new grpc::Method<global::Games.Cheetah.Realtime.GRPC.DeleteMemberRequest, global::Games.Cheetah.Realtime.GRPC.DeleteMemberResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteMember",
        __Marshaller_cheetah_matches_realtime_grpc_DeleteMemberRequest,
        __Marshaller_cheetah_matches_realtime_grpc_DeleteMemberResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Games.Cheetah.Realtime.GRPC.CreateSuperMemberRequest, global::Games.Cheetah.Realtime.GRPC.CreateMemberResponse> __Method_CreateSuperMember = new grpc::Method<global::Games.Cheetah.Realtime.GRPC.CreateSuperMemberRequest, global::Games.Cheetah.Realtime.GRPC.CreateMemberResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateSuperMember",
        __Marshaller_cheetah_matches_realtime_grpc_CreateSuperMemberRequest,
        __Marshaller_cheetah_matches_realtime_grpc_CreateMemberResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Games.Cheetah.Realtime.GRPC.ProbeRequest, global::Games.Cheetah.Realtime.GRPC.ProbeResponse> __Method_Probe = new grpc::Method<global::Games.Cheetah.Realtime.GRPC.ProbeRequest, global::Games.Cheetah.Realtime.GRPC.ProbeResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Probe",
        __Marshaller_cheetah_matches_realtime_grpc_ProbeRequest,
        __Marshaller_cheetah_matches_realtime_grpc_ProbeResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Games.Cheetah.Realtime.GRPC.EmptyRequest, global::Games.Cheetah.Realtime.GRPC.GetRoomsResponse> __Method_GetRooms = new grpc::Method<global::Games.Cheetah.Realtime.GRPC.EmptyRequest, global::Games.Cheetah.Realtime.GRPC.GetRoomsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetRooms",
        __Marshaller_cheetah_matches_realtime_grpc_EmptyRequest,
        __Marshaller_cheetah_matches_realtime_grpc_GetRoomsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Games.Cheetah.Realtime.GRPC.DeleteRoomRequest, global::Games.Cheetah.Realtime.GRPC.DeleteRoomResponse> __Method_DeleteRoom = new grpc::Method<global::Games.Cheetah.Realtime.GRPC.DeleteRoomRequest, global::Games.Cheetah.Realtime.GRPC.DeleteRoomResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteRoom",
        __Marshaller_cheetah_matches_realtime_grpc_DeleteRoomRequest,
        __Marshaller_cheetah_matches_realtime_grpc_DeleteRoomResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Games.Cheetah.Realtime.GRPC.EmptyRequest, global::Games.Cheetah.Realtime.GRPC.GetRoomsMembersCountResponse> __Method_GetRoomsMembersCount = new grpc::Method<global::Games.Cheetah.Realtime.GRPC.EmptyRequest, global::Games.Cheetah.Realtime.GRPC.GetRoomsMembersCountResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetRoomsMembersCount",
        __Marshaller_cheetah_matches_realtime_grpc_EmptyRequest,
        __Marshaller_cheetah_matches_realtime_grpc_GetRoomsMembersCountResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Games.Cheetah.Realtime.GRPC.ServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of RealtimeServerManagementService</summary>
    [grpc::BindServiceMethod(typeof(RealtimeServerManagementService), "BindService")]
    public abstract partial class RealtimeServerManagementServiceBase
    {
      /// <summary>
      ///*
      ///Создать комнату
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Games.Cheetah.Realtime.GRPC.RoomIdResponse> CreateRoom(global::Games.Cheetah.Realtime.GRPC.RoomTemplate request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///*
      ///Присоединить пользователя к комнате, после этого комната будет ожидать udp соединения
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Games.Cheetah.Realtime.GRPC.CreateMemberResponse> CreateMember(global::Games.Cheetah.Realtime.GRPC.CreateMemberRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///*
      ///Удалить пользователя из комнаты и закрыть соединение
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Games.Cheetah.Realtime.GRPC.DeleteMemberResponse> DeleteMember(global::Games.Cheetah.Realtime.GRPC.DeleteMemberRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///*
      ///Создать супер пользователя, для него отключены проверки всех прав
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Games.Cheetah.Realtime.GRPC.CreateMemberResponse> CreateSuperMember(global::Games.Cheetah.Realtime.GRPC.CreateSuperMemberRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///*
      ///Проверить живой ли сервер
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Games.Cheetah.Realtime.GRPC.ProbeResponse> Probe(global::Games.Cheetah.Realtime.GRPC.ProbeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///*
      ///Отслеживание операций создания комнаты, при первом вызове отсылаются и уже созданные комнаты.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Games.Cheetah.Realtime.GRPC.GetRoomsResponse> GetRooms(global::Games.Cheetah.Realtime.GRPC.EmptyRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///*
      ///Отключить всех пользователей от комнаты и удалить её
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Games.Cheetah.Realtime.GRPC.DeleteRoomResponse> DeleteRoom(global::Games.Cheetah.Realtime.GRPC.DeleteRoomRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Games.Cheetah.Realtime.GRPC.GetRoomsMembersCountResponse> GetRoomsMembersCount(global::Games.Cheetah.Realtime.GRPC.EmptyRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for RealtimeServerManagementService</summary>
    public partial class RealtimeServerManagementServiceClient : grpc::ClientBase<RealtimeServerManagementServiceClient>
    {
      /// <summary>Creates a new client for RealtimeServerManagementService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public RealtimeServerManagementServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for RealtimeServerManagementService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public RealtimeServerManagementServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected RealtimeServerManagementServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected RealtimeServerManagementServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      ///*
      ///Создать комнату
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Games.Cheetah.Realtime.GRPC.RoomIdResponse CreateRoom(global::Games.Cheetah.Realtime.GRPC.RoomTemplate request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateRoom(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///*
      ///Создать комнату
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Games.Cheetah.Realtime.GRPC.RoomIdResponse CreateRoom(global::Games.Cheetah.Realtime.GRPC.RoomTemplate request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateRoom, null, options, request);
      }
      /// <summary>
      ///*
      ///Создать комнату
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Games.Cheetah.Realtime.GRPC.RoomIdResponse> CreateRoomAsync(global::Games.Cheetah.Realtime.GRPC.RoomTemplate request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateRoomAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///*
      ///Создать комнату
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Games.Cheetah.Realtime.GRPC.RoomIdResponse> CreateRoomAsync(global::Games.Cheetah.Realtime.GRPC.RoomTemplate request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateRoom, null, options, request);
      }
      /// <summary>
      ///*
      ///Присоединить пользователя к комнате, после этого комната будет ожидать udp соединения
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Games.Cheetah.Realtime.GRPC.CreateMemberResponse CreateMember(global::Games.Cheetah.Realtime.GRPC.CreateMemberRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateMember(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///*
      ///Присоединить пользователя к комнате, после этого комната будет ожидать udp соединения
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Games.Cheetah.Realtime.GRPC.CreateMemberResponse CreateMember(global::Games.Cheetah.Realtime.GRPC.CreateMemberRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateMember, null, options, request);
      }
      /// <summary>
      ///*
      ///Присоединить пользователя к комнате, после этого комната будет ожидать udp соединения
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Games.Cheetah.Realtime.GRPC.CreateMemberResponse> CreateMemberAsync(global::Games.Cheetah.Realtime.GRPC.CreateMemberRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateMemberAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///*
      ///Присоединить пользователя к комнате, после этого комната будет ожидать udp соединения
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Games.Cheetah.Realtime.GRPC.CreateMemberResponse> CreateMemberAsync(global::Games.Cheetah.Realtime.GRPC.CreateMemberRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateMember, null, options, request);
      }
      /// <summary>
      ///*
      ///Удалить пользователя из комнаты и закрыть соединение
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Games.Cheetah.Realtime.GRPC.DeleteMemberResponse DeleteMember(global::Games.Cheetah.Realtime.GRPC.DeleteMemberRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteMember(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///*
      ///Удалить пользователя из комнаты и закрыть соединение
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Games.Cheetah.Realtime.GRPC.DeleteMemberResponse DeleteMember(global::Games.Cheetah.Realtime.GRPC.DeleteMemberRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteMember, null, options, request);
      }
      /// <summary>
      ///*
      ///Удалить пользователя из комнаты и закрыть соединение
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Games.Cheetah.Realtime.GRPC.DeleteMemberResponse> DeleteMemberAsync(global::Games.Cheetah.Realtime.GRPC.DeleteMemberRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteMemberAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///*
      ///Удалить пользователя из комнаты и закрыть соединение
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Games.Cheetah.Realtime.GRPC.DeleteMemberResponse> DeleteMemberAsync(global::Games.Cheetah.Realtime.GRPC.DeleteMemberRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteMember, null, options, request);
      }
      /// <summary>
      ///*
      ///Создать супер пользователя, для него отключены проверки всех прав
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Games.Cheetah.Realtime.GRPC.CreateMemberResponse CreateSuperMember(global::Games.Cheetah.Realtime.GRPC.CreateSuperMemberRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateSuperMember(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///*
      ///Создать супер пользователя, для него отключены проверки всех прав
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Games.Cheetah.Realtime.GRPC.CreateMemberResponse CreateSuperMember(global::Games.Cheetah.Realtime.GRPC.CreateSuperMemberRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateSuperMember, null, options, request);
      }
      /// <summary>
      ///*
      ///Создать супер пользователя, для него отключены проверки всех прав
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Games.Cheetah.Realtime.GRPC.CreateMemberResponse> CreateSuperMemberAsync(global::Games.Cheetah.Realtime.GRPC.CreateSuperMemberRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateSuperMemberAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///*
      ///Создать супер пользователя, для него отключены проверки всех прав
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Games.Cheetah.Realtime.GRPC.CreateMemberResponse> CreateSuperMemberAsync(global::Games.Cheetah.Realtime.GRPC.CreateSuperMemberRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateSuperMember, null, options, request);
      }
      /// <summary>
      ///*
      ///Проверить живой ли сервер
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Games.Cheetah.Realtime.GRPC.ProbeResponse Probe(global::Games.Cheetah.Realtime.GRPC.ProbeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Probe(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///*
      ///Проверить живой ли сервер
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Games.Cheetah.Realtime.GRPC.ProbeResponse Probe(global::Games.Cheetah.Realtime.GRPC.ProbeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Probe, null, options, request);
      }
      /// <summary>
      ///*
      ///Проверить живой ли сервер
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Games.Cheetah.Realtime.GRPC.ProbeResponse> ProbeAsync(global::Games.Cheetah.Realtime.GRPC.ProbeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ProbeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///*
      ///Проверить живой ли сервер
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Games.Cheetah.Realtime.GRPC.ProbeResponse> ProbeAsync(global::Games.Cheetah.Realtime.GRPC.ProbeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Probe, null, options, request);
      }
      /// <summary>
      ///*
      ///Отслеживание операций создания комнаты, при первом вызове отсылаются и уже созданные комнаты.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Games.Cheetah.Realtime.GRPC.GetRoomsResponse GetRooms(global::Games.Cheetah.Realtime.GRPC.EmptyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRooms(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///*
      ///Отслеживание операций создания комнаты, при первом вызове отсылаются и уже созданные комнаты.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Games.Cheetah.Realtime.GRPC.GetRoomsResponse GetRooms(global::Games.Cheetah.Realtime.GRPC.EmptyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetRooms, null, options, request);
      }
      /// <summary>
      ///*
      ///Отслеживание операций создания комнаты, при первом вызове отсылаются и уже созданные комнаты.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Games.Cheetah.Realtime.GRPC.GetRoomsResponse> GetRoomsAsync(global::Games.Cheetah.Realtime.GRPC.EmptyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRoomsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///*
      ///Отслеживание операций создания комнаты, при первом вызове отсылаются и уже созданные комнаты.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Games.Cheetah.Realtime.GRPC.GetRoomsResponse> GetRoomsAsync(global::Games.Cheetah.Realtime.GRPC.EmptyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetRooms, null, options, request);
      }
      /// <summary>
      ///*
      ///Отключить всех пользователей от комнаты и удалить её
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Games.Cheetah.Realtime.GRPC.DeleteRoomResponse DeleteRoom(global::Games.Cheetah.Realtime.GRPC.DeleteRoomRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteRoom(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///*
      ///Отключить всех пользователей от комнаты и удалить её
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Games.Cheetah.Realtime.GRPC.DeleteRoomResponse DeleteRoom(global::Games.Cheetah.Realtime.GRPC.DeleteRoomRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteRoom, null, options, request);
      }
      /// <summary>
      ///*
      ///Отключить всех пользователей от комнаты и удалить её
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Games.Cheetah.Realtime.GRPC.DeleteRoomResponse> DeleteRoomAsync(global::Games.Cheetah.Realtime.GRPC.DeleteRoomRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteRoomAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///*
      ///Отключить всех пользователей от комнаты и удалить её
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Games.Cheetah.Realtime.GRPC.DeleteRoomResponse> DeleteRoomAsync(global::Games.Cheetah.Realtime.GRPC.DeleteRoomRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteRoom, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Games.Cheetah.Realtime.GRPC.GetRoomsMembersCountResponse GetRoomsMembersCount(global::Games.Cheetah.Realtime.GRPC.EmptyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRoomsMembersCount(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Games.Cheetah.Realtime.GRPC.GetRoomsMembersCountResponse GetRoomsMembersCount(global::Games.Cheetah.Realtime.GRPC.EmptyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetRoomsMembersCount, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Games.Cheetah.Realtime.GRPC.GetRoomsMembersCountResponse> GetRoomsMembersCountAsync(global::Games.Cheetah.Realtime.GRPC.EmptyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRoomsMembersCountAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Games.Cheetah.Realtime.GRPC.GetRoomsMembersCountResponse> GetRoomsMembersCountAsync(global::Games.Cheetah.Realtime.GRPC.EmptyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetRoomsMembersCount, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override RealtimeServerManagementServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new RealtimeServerManagementServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(RealtimeServerManagementServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CreateRoom, serviceImpl.CreateRoom)
          .AddMethod(__Method_CreateMember, serviceImpl.CreateMember)
          .AddMethod(__Method_DeleteMember, serviceImpl.DeleteMember)
          .AddMethod(__Method_CreateSuperMember, serviceImpl.CreateSuperMember)
          .AddMethod(__Method_Probe, serviceImpl.Probe)
          .AddMethod(__Method_GetRooms, serviceImpl.GetRooms)
          .AddMethod(__Method_DeleteRoom, serviceImpl.DeleteRoom)
          .AddMethod(__Method_GetRoomsMembersCount, serviceImpl.GetRoomsMembersCount).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, RealtimeServerManagementServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CreateRoom, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Games.Cheetah.Realtime.GRPC.RoomTemplate, global::Games.Cheetah.Realtime.GRPC.RoomIdResponse>(serviceImpl.CreateRoom));
      serviceBinder.AddMethod(__Method_CreateMember, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Games.Cheetah.Realtime.GRPC.CreateMemberRequest, global::Games.Cheetah.Realtime.GRPC.CreateMemberResponse>(serviceImpl.CreateMember));
      serviceBinder.AddMethod(__Method_DeleteMember, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Games.Cheetah.Realtime.GRPC.DeleteMemberRequest, global::Games.Cheetah.Realtime.GRPC.DeleteMemberResponse>(serviceImpl.DeleteMember));
      serviceBinder.AddMethod(__Method_CreateSuperMember, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Games.Cheetah.Realtime.GRPC.CreateSuperMemberRequest, global::Games.Cheetah.Realtime.GRPC.CreateMemberResponse>(serviceImpl.CreateSuperMember));
      serviceBinder.AddMethod(__Method_Probe, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Games.Cheetah.Realtime.GRPC.ProbeRequest, global::Games.Cheetah.Realtime.GRPC.ProbeResponse>(serviceImpl.Probe));
      serviceBinder.AddMethod(__Method_GetRooms, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Games.Cheetah.Realtime.GRPC.EmptyRequest, global::Games.Cheetah.Realtime.GRPC.GetRoomsResponse>(serviceImpl.GetRooms));
      serviceBinder.AddMethod(__Method_DeleteRoom, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Games.Cheetah.Realtime.GRPC.DeleteRoomRequest, global::Games.Cheetah.Realtime.GRPC.DeleteRoomResponse>(serviceImpl.DeleteRoom));
      serviceBinder.AddMethod(__Method_GetRoomsMembersCount, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Games.Cheetah.Realtime.GRPC.EmptyRequest, global::Games.Cheetah.Realtime.GRPC.GetRoomsMembersCountResponse>(serviceImpl.GetRoomsMembersCount));
    }

  }
}
#endregion
