theme:
  name: material
  language: ru
  features:
    - navigation.top
    - navigation.instant
  palette:
    scheme: slate
    primary: amber
repo_url: https://github.com/cheetah-game-platform/platform
site_name: Cheetah Game Platform
docs_dir: content
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
plugins:
  - search:
      lang: ru
extra_css:
  - extra/extra.css
nav:
  - "Введение": "index.md"
  - "Unity":
      - "Настройка": "unity/setup.md"
  - "Матчи реального времени":
      - "Введение": "modules/matches/realtime/index.md"
      - "Базовые понятия":
          - "Клиент": "modules/matches/realtime/basics/client.md"
          - "Комната": "modules/matches/realtime/basics/room.md"
          - "Объект": "modules/matches/realtime/basics/object.md"
          - "Канал": "modules/matches/realtime/basics/channel.md"
      - "Команды":
          - "События": "modules/matches/realtime/commands/event.md"
          - "Структуры": "modules/matches/realtime/commands/structure.md"
          - "Целые числа": "modules/matches/realtime/commands/long.md"
          - "Вещественные числа": "modules/matches/realtime/commands/double.md"
          - "Сериализация": "modules/matches/realtime/commands/serialization.md"
          - "Удаление поля": "modules/matches/realtime/commands/delete_field.md"
          - "CompareAndSet": "modules/matches/realtime/commands/compare_and_set.md"
      - "Конфигурация": "modules/matches/realtime/configuration.md"
      - "Локальная разработка":
          - "Эмуляция параметров сети": "modules/matches/realtime/develop/network.md"
          - "Логирование": "modules/matches/realtime/develop/logger.md"
          - "Панель сетевых команд": "modules/matches/realtime/develop/commands-panel.md"
          - "Просмотр состояния сервера": "modules/matches/realtime/develop/dump-panel.md"
      - "Тестирование":
          - "Интеграционное": "modules/matches/realtime/test/integration.md"
      - "Плагины": "modules/matches/realtime/plugins/index.md"

