// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: internal.proto
// </auto-generated>
// Original file comments:
// API для создания токенов
// Для внутреннего использования
//
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Cheetah.Auth.Cerberus.Internal {
  public static partial class Cerberus
  {
    static readonly string __ServiceName = "cheetah.auth.cerberus.internal.Cerberus";

    static readonly grpc::Marshaller<global::Cheetah.Auth.Cerberus.Internal.CreateTokenRequest> __Marshaller_cheetah_auth_cerberus_internal_CreateTokenRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Cheetah.Auth.Cerberus.Internal.CreateTokenRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Cheetah.Auth.Cerberus.Types.Tokens> __Marshaller_cheetah_auth_cerberus_types_Tokens = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Cheetah.Auth.Cerberus.Types.Tokens.Parser.ParseFrom);

    static readonly grpc::Method<global::Cheetah.Auth.Cerberus.Internal.CreateTokenRequest, global::Cheetah.Auth.Cerberus.Types.Tokens> __Method_create = new grpc::Method<global::Cheetah.Auth.Cerberus.Internal.CreateTokenRequest, global::Cheetah.Auth.Cerberus.Types.Tokens>(
        grpc::MethodType.Unary,
        __ServiceName,
        "create",
        __Marshaller_cheetah_auth_cerberus_internal_CreateTokenRequest,
        __Marshaller_cheetah_auth_cerberus_types_Tokens);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Cheetah.Auth.Cerberus.Internal.InternalReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Cerberus</summary>
    [grpc::BindServiceMethod(typeof(Cerberus), "BindService")]
    public abstract partial class CerberusBase
    {
      /// <summary>
      ///*
      /// Создать пару токенов session/refresh
      /// Вызывается из других микросервисов
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Cheetah.Auth.Cerberus.Types.Tokens> create(global::Cheetah.Auth.Cerberus.Internal.CreateTokenRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Cerberus</summary>
    public partial class CerberusClient : grpc::ClientBase<CerberusClient>
    {
      /// <summary>Creates a new client for Cerberus</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public CerberusClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Cerberus that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public CerberusClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected CerberusClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected CerberusClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      ///*
      /// Создать пару токенов session/refresh
      /// Вызывается из других микросервисов
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Cheetah.Auth.Cerberus.Types.Tokens create(global::Cheetah.Auth.Cerberus.Internal.CreateTokenRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return create(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///*
      /// Создать пару токенов session/refresh
      /// Вызывается из других микросервисов
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Cheetah.Auth.Cerberus.Types.Tokens create(global::Cheetah.Auth.Cerberus.Internal.CreateTokenRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_create, null, options, request);
      }
      /// <summary>
      ///*
      /// Создать пару токенов session/refresh
      /// Вызывается из других микросервисов
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Cheetah.Auth.Cerberus.Types.Tokens> createAsync(global::Cheetah.Auth.Cerberus.Internal.CreateTokenRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return createAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///*
      /// Создать пару токенов session/refresh
      /// Вызывается из других микросервисов
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Cheetah.Auth.Cerberus.Types.Tokens> createAsync(global::Cheetah.Auth.Cerberus.Internal.CreateTokenRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_create, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override CerberusClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new CerberusClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(CerberusBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_create, serviceImpl.create).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, CerberusBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_create, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Cheetah.Auth.Cerberus.Internal.CreateTokenRequest, global::Cheetah.Auth.Cerberus.Types.Tokens>(serviceImpl.create));
    }

  }
}
#endregion
