[package]
name = "cheetah-matches-realtime-client"
version = "0.0.1"
authors = ["kviring <alex@kviring.com>"]
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "lib"]

[dependencies]
lazy_static = "1.4.0"
cheetah-matches-realtime-common = { path = "../../common/Common" }
widestring = "0.5.1"
fnv = "1.0.7"
heapless = { version = "0.7.15", features = ["serde"] }
thiserror = "1.0.30"
tracing = "0.1.31"
tracing-core = "0.1.22"
tracing-log = { version = "0.1.2" }
tracing-subscriber = { version = "0.3.9", features = ["env-filter"] }


[dev-dependencies]
cheetah-matches-realtime = { path = "../../server/" }
easybench = "1.0.0"
rand = "0.8.3"