[package]
name = "cheetah-matches-factory"
version = "999.999.999"
edition = "2021"

[[bin]]
name = "cheetah-matches-factory-server"
path = "src/bin/service.rs"

[lib]
doctest = false

[dependencies]
tokio = { version = "1.16.1", features = ["rt-multi-thread", "time", "fs", "macros", "net"] }
tonic = "0.6.2"
tonic-health = "0.5.0"
prost = "0.9.0"
cheetah-libraries-microservice = { path = "../../../libraries/Microservice/" }
serde = { version = "1.0.140", features = ["derive", "rc"] }
serde_yaml = "0.8.23"
rmp-serde = "1.1.0"
rmpv = { version = "1.0.0", features = ["with-serde"] }
tokio-stream = { version = "0.1.8", features = ["net"] }
futures = "0.3.21"
tonic-web = "0.2.0"
thiserror = "1.0"
tracing = "0.1.31"
prometheus = "0.13.1"
lazy_static = "1.4.0"

[dev-dependencies]
tempfile = "3.3.0"
include_dir = "0.7.2"

[build-dependencies]
tonic-build = "0.6.2"
