apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: 1
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        prometheus: "true"
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "ghcr.io/cheetah-game-platform/platform/{{ .Chart.Name }}:{{ .Values.global.platformImageVersion }}"
          imagePullPolicy: Always
          securityContext:
            readOnlyRootFilesystem: true
          resources:
            limits:
              cpu: {{ .Values.cpu.limit }}
              memory: 40Mi
            requests:
              cpu: {{ .Values.cpu.request }}
              memory: 20Mi
          env:
            - name: "JWT_PUBLIC_KEY"
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: public
          ports:
            - name: prometheus
              containerPort: 3000
              protocol: TCP