using Cheetah.Matches.Realtime.Codec;
using Cheetah.Matches.Realtime.Codec.Formatter;
using Cheetah.Matches.Realtime.Types;
using UnityEngine;
using Shared.Types;

// ReSharper disable once CheckNamespace
namespace Shared.Types
{
		// warning warning warning warning warning
		// Code generated by Cheetah relay codec generator - DO NOT EDIT
		// warning warning warning warning warning
		public class TurretsParamsStructureCodec:Codec<Shared.Types.TurretsParamsStructure>
		{
			public void Decode(ref CheetahBuffer buffer, ref Shared.Types.TurretsParamsStructure dest)
			{
				dest.Speed = DoubleFormatter.Instance.Read(ref buffer);
				dest.Damage = DoubleFormatter.Instance.Read(ref buffer);
			}
	
			public void  Encode(ref Shared.Types.TurretsParamsStructure source, ref CheetahBuffer buffer)
			{
				DoubleFormatter.Instance.Write(source.Speed,ref buffer);
				DoubleFormatter.Instance.Write(source.Damage,ref buffer);
			}
	
	
			[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]
			private static void OnRuntimeMethodLoad()
			{
				CodecRegistryBuilder.RegisterDefault(factory=>new TurretsParamsStructureCodec());
			}
	
		}
	
	
}
