[package]
name = "cheetah-matches-realtime-common"
version = "0.1.0"
authors = ["Kviring Aleksey <alex@kviring.com>"]
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
rand = "0.8.3"
snap = "1.0.5"
byteorder = "1.4.3"
chacha20poly1305 = { version = "0.9.1", features = ["heapless","reduced-round"] }
cheetah-matches-realtime-macro = { path = "../Macro/" }
generic-array = "0.14.5"
heapless = { version = "0.7.8"}
fnv = "1.0.7"
strum_macros = "0.24.2"
thiserror = "1.0.30"
hash32 = "0.2.1"
hash32-derive = "0.1.1"
tracing = "0.1.31"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "frame_codec"
harness = false