[package]
name = "cheetah-matches-realtime-common"
authors.workspace = true
edition.workspace = true
version = "0.1.0"

[dependencies]
lazy_static.workspace = true
rand.workspace = true
snap = "1.0.5"
byteorder = "1.4.3"
chacha20poly1305 = { version = "0.9.0", features = ["heapless", "reduced-round"] }
cheetah-matches-realtime-macro = { path = "../Macro" }
generic-array = "0.14.5"
heapless.workspace = true
fnv.workspace = true
strum_macros.workspace = true
thiserror.workspace = true
hash32 = "0.2.1"
hash32-derive = "0.1.1"
tracing.workspace = true
log.workspace = true
tracing-core.workspace = true
tracing-log.workspace = true
tracing-subscriber.workspace = true
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "frame_codec"
harness = false
