# https://github.com/ericseppanen/cargo-cranky
# cargo install cargo-cranky && cargo cranky

deny = [
]

warn = [
    "clippy::all",
    "clippy::pedantic",
    "clippy::restriction",

    # https://doc.rust-lang.org/rustc/lints/groups.html
    # rustc -W help
    "warnings",
    "future-incompatible",
    "nonstandard-style",
    "rust-2018-compatibility",
    "rust-2018-idioms",
    "rust-2021-compatibility",
    "unused",
    # https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html
    "macro_use_extern_crate",
    "meta_variable_misuse",
    "missing_abi",
    "non_ascii_idents",
    "noop_method_call",
    "single_use_lifetimes",
    "trivial_casts",
    "trivial_numeric_casts",
    "unsafe_op_in_unsafe_fn",
    "unstable_features",
    "unused_import_braces",
    "unused_lifetimes",
    "unused_tuple_struct_fields",
]

allow = [
    # clippy::style exceptions
    "clippy::missing_safety_doc",
    # clippy::pedantic exceptions
    "clippy::default_trait_access", # todo
    "clippy::implicit_hasher", # todo
    "clippy::match_same_arms",
    "clippy::missing_errors_doc",
    "clippy::missing_panics_doc",
    "clippy::module_name_repetitions",
    "clippy::similar_names",
    "clippy::too_many_lines",
    # clippy::restriction exceptions
    "clippy::arithmetic_side_effects",
    "clippy::as_conversions",
    "clippy::decimal_literal_representation",
    "clippy::default_numeric_fallback",
    "clippy::exhaustive_enums",
    "clippy::exhaustive_structs",
    "clippy::expect_used", # todo
    "clippy::float_arithmetic",
    "clippy::implicit_return",
    "clippy::indexing_slicing", # todo
    "clippy::integer_arithmetic",
    "clippy::integer_division",
    "clippy::let_underscore_must_use",
    "clippy::missing_docs_in_private_items",
    "clippy::missing_inline_in_public_items",
    "clippy::mod_module_files",
    "clippy::modulo_arithmetic",
    "clippy::multiple_inherent_impl", # todo
    "clippy::non_ascii_literal",
    "clippy::panic", # todo
    "clippy::panic_in_result_fn",
    "clippy::pattern_type_mismatch",
    "clippy::pub_use",
    "clippy::self_named_module_files",
    "clippy::separated_literal_suffix", # we use clippy::unseparated_literal_suffix instead
    "clippy::shadow_reuse",
    "clippy::shadow_unrelated", # todo
    "clippy::single_char_lifetime_names",
    "clippy::std_instead_of_alloc",
    "clippy::std_instead_of_core",
    "clippy::string_slice", # todo
    "clippy::undocumented_unsafe_blocks",
    "clippy::unwrap_used", # todo
    "clippy::wildcard_enum_match_arm", # todo
]
