[package]
name = "cheetah-matches-stub-registry"
version = "999.999.999"
edition = "2021"

[[bin]]
name = "cheetah-matches-stubregistry-server"
path = "src/bin/service.rs"

[dependencies]
tokio = { version = "1.16.1", features = ["rt-multi-thread", "time", "fs", "macros", "net"] }
tonic = "0.6.2"
prost = "0.9.0"
cheetah-libraries-microservice = { path = "../../../libraries/rust/Microservice" }
tracing = "0.1.31"

[build-dependencies]
tonic-build = "0.6.2"
