[package]
name = "cheetah-matches-realtime-embedded"
version = "0.1.0"
authors = ["kviring <alex@kviring.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib","staticlib"]


[dependencies]
cheetah-matches-realtime-common = { path = "../../../common/Common" }
cheetah-matches-realtime = { path = "../../../server" }
tokio = { version = "1.16.1", features = ["rt-multi-thread", "time", "fs", "macros", "net", "sync"] }
anyhow = "1.0.64"
thiserror = "1.0.34"
lazy_static = "1.4.0"
port_scanner = "0.1.5"
widestring = "0.5.1"
log = "0.4.14"
tracing = "0.1.31"
tracing-core = "0.1.26"
tracing-log = { version = "0.1.2" }
tracing-subscriber = { version = "0.3.9", features = ["env-filter"] }


[build-dependencies]
tonic-build = { version = "0.6.2", features = ["rustfmt"] }
