using Cheetah.Matches.Relay.Codec;
using Cheetah.Matches.Relay.Codec.Formatter;
using Cheetah.Matches.Relay.Types;
using UnityEngine;
using Cheetah.Matches.Relay.Tests.Runtime.Codec.Field;

// ReSharper disable once CheckNamespace
namespace Cheetah.Matches.Relay.Tests.Runtime.Codec.Field
{
		// warning warning warning warning warning
		// Code generated by Cheetah relay codec generator - DO NOT EDIT
		// warning warning warning warning warning
		public class TestCodecFieldStructureCodec:Codec<Cheetah.Matches.Relay.Tests.Runtime.Codec.Field.TestCodecField.Structure>
		{
			public void Decode(ref CheetahBuffer buffer, ref Cheetah.Matches.Relay.Tests.Runtime.Codec.Field.TestCodecField.Structure dest)
			{
				codec0.Decode(ref buffer, ref dest.innerValue);
			}
	
			public void  Encode(ref Cheetah.Matches.Relay.Tests.Runtime.Codec.Field.TestCodecField.Structure source, ref CheetahBuffer buffer)
			{
				codec0.Encode(ref source.innerValue, ref buffer);
			}
	
			private readonly Codec<Cheetah.Matches.Relay.Tests.Runtime.Codec.Field.TestCodecField.Inner> codec0;
	
			private TestCodecFieldStructureCodec(CodecRegistry codecRegistry)
			{
				codec0 = codecRegistry.GetCodec<Cheetah.Matches.Relay.Tests.Runtime.Codec.Field.TestCodecField.Inner>();
			}
	
	
			[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]
			private static void OnRuntimeMethodLoad()
			{
				CodecRegistryBuilder.RegisterDefault(factory=>new TestCodecFieldStructureCodec(factory));
			}
	
		}
	
	
}
