[package]
name = "cheetah-matches-registry"
authors.workspace = true
edition.workspace = true
version = "999.999.999"

[[bin]]
name = "cheetah-matches-registry-server"
path = "src/bin/main.rs"

[dependencies]
pin-project = "1.0.10"
pin-project-internal = "1.0.10"
tokio = { workspace = true, features = ["rt-multi-thread", "time", "fs", "macros", "net"] }
tonic.workspace = true
tonic-health.workspace = true
prost.workspace = true
cheetah-libraries-microservice = { path = "../../../libraries/rust/Microservice" }
thiserror.workspace = true
hostname = "^0.3"
redis = { version = "0.22.1", features = ["tokio-comp"] }
futures.workspace = true
async-trait = "0.1.52"
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tracing.workspace = true

[dev-dependencies]
testcontainers = "0.12.0"
lazy_static.workspace = true

[build-dependencies]
tonic-build.workspace = true
protobuf-src.workspace = true
