[package]
name = "cheetah-accounts"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "cheetah-accounts"
path = "src/bin/service.rs"


[dependencies]
base64 = "0.13.0"
chrono = "0.4"
tonic = "0.6.2"
tonic-health = "0.5.0"
prost = "0.9.0"
tokio = { version = "1.16.1", features = ["rt-multi-thread", "time", "fs", "macros", "net"] }
tokio-stream = { version = "0.1.8", features = ["net"] }
async-stream = "0.3"
jsonwebtoken = "8.0.1"
serde = { version = "1.0.132", features = ["derive"] }
cheetah-libraries-microservice = { path = "../../../libraries/Microservice" }
ydb-steroids = { version = "0.1.2", features = ["uuid"] }
ydb = "0.2.0"
async-trait = "0.1.52"
lazy_static = "1.4.0"
tonic-web = "0.2.0"
rand = "0.8"
tracing = "0.1.31"
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
headers = "0.3.1"
rustls = { version = "0.20.2" }
thiserror = "1.0.30"
prometheus = "0.13.0"
uuid = { version = "1.0.0", features = ["v4", "serde"] }
include_dir = "0.7.2"
anyhow = "1.0.57"
jwt-tonic-user-uuid = "0.0.1"


[dev-dependencies]
testcontainers = "0.13.0"
lazy_static = "1.4.0"
futures = "0.3.21"
httpmock = { version = "0.6.2" }
base64 = { version = "0.13.0" }
ydb-steroids = { version = "0.1.2", features = ["test_container"] }
rsa = "0.5.0"

[build-dependencies]
tonic-build = { version = "0.6.2", features = ["rustfmt"] }
