apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        prometheus: "true"
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "ghcr.io/cheetah-game-platform/platform/user-accounts:{{ .Chart.Version }}"
          resources:
            limits:
              cpu: {{ .Values.cpu.limit }}
              memory: {{ .Values.memory.limit }}
            requests:
              cpu: {{ .Values.cpu.request }}
              memory: {{ .Values.memory.request }}
          imagePullPolicy: Always
          startupProbe:
            exec:
              command: [ "/bin/grpc_health_probe", "-addr=:5000" ]
            initialDelaySeconds: 5
          livenessProbe:
            exec:
              command: [ "/bin/grpc_health_probe", "-addr=:5000" ]
            initialDelaySeconds: 10
          securityContext:
            readOnlyRootFilesystem: true
          env:
            {{- range $item := .Values.env }}
            - {{- $item | toYaml | nindent 13 }}
            {{- end }}
            - name: "JWT_PUBLIC_KEY"
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: public
            - name: "JWT_PRIVATE_KEY"
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: private
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOKI_URL
              value: {{.Values.lokiUrl}}
          ports:
            - name: prometheus
              containerPort: 3000
              protocol: TCP
