// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Games.Cheetah.Auth.External.Google {
  public static partial class Google
  {
    static readonly string __ServiceName = "games.cheetah.auth.external.google.Google";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Games.Cheetah.Auth.External.Google.RegistryOrLoginRequest> __Marshaller_games_cheetah_auth_external_google_RegistryOrLoginRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Games.Cheetah.Auth.External.Google.RegistryOrLoginRequest.Parser));
    static readonly grpc::Marshaller<global::Games.Cheetah.Cerberus.Types.Tokens> __Marshaller_games_cheetah_cerberus_types_Tokens = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Games.Cheetah.Cerberus.Types.Tokens.Parser));
    static readonly grpc::Marshaller<global::Games.Cheetah.Auth.External.Google.AttachRequest> __Marshaller_games_cheetah_auth_external_google_AttachRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Games.Cheetah.Auth.External.Google.AttachRequest.Parser));
    static readonly grpc::Marshaller<global::Games.Cheetah.Auth.External.Google.AttachResponse> __Marshaller_games_cheetah_auth_external_google_AttachResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Games.Cheetah.Auth.External.Google.AttachResponse.Parser));

    static readonly grpc::Method<global::Games.Cheetah.Auth.External.Google.RegistryOrLoginRequest, global::Games.Cheetah.Cerberus.Types.Tokens> __Method_RegistryOrLogin = new grpc::Method<global::Games.Cheetah.Auth.External.Google.RegistryOrLoginRequest, global::Games.Cheetah.Cerberus.Types.Tokens>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RegistryOrLogin",
        __Marshaller_games_cheetah_auth_external_google_RegistryOrLoginRequest,
        __Marshaller_games_cheetah_cerberus_types_Tokens);

    static readonly grpc::Method<global::Games.Cheetah.Auth.External.Google.AttachRequest, global::Games.Cheetah.Auth.External.Google.AttachResponse> __Method_Attach = new grpc::Method<global::Games.Cheetah.Auth.External.Google.AttachRequest, global::Games.Cheetah.Auth.External.Google.AttachResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Attach",
        __Marshaller_games_cheetah_auth_external_google_AttachRequest,
        __Marshaller_games_cheetah_auth_external_google_AttachResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Games.Cheetah.Auth.External.Google.GoogleReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Google</summary>
    [grpc::BindServiceMethod(typeof(Google), "BindService")]
    public abstract partial class GoogleBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Games.Cheetah.Cerberus.Types.Tokens> RegistryOrLogin(global::Games.Cheetah.Auth.External.Google.RegistryOrLoginRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Games.Cheetah.Auth.External.Google.AttachResponse> Attach(global::Games.Cheetah.Auth.External.Google.AttachRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Google</summary>
    public partial class GoogleClient : grpc::ClientBase<GoogleClient>
    {
      /// <summary>Creates a new client for Google</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public GoogleClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Google that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public GoogleClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected GoogleClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected GoogleClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Games.Cheetah.Cerberus.Types.Tokens RegistryOrLogin(global::Games.Cheetah.Auth.External.Google.RegistryOrLoginRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RegistryOrLogin(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Games.Cheetah.Cerberus.Types.Tokens RegistryOrLogin(global::Games.Cheetah.Auth.External.Google.RegistryOrLoginRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RegistryOrLogin, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Games.Cheetah.Cerberus.Types.Tokens> RegistryOrLoginAsync(global::Games.Cheetah.Auth.External.Google.RegistryOrLoginRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RegistryOrLoginAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Games.Cheetah.Cerberus.Types.Tokens> RegistryOrLoginAsync(global::Games.Cheetah.Auth.External.Google.RegistryOrLoginRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RegistryOrLogin, null, options, request);
      }
      public virtual global::Games.Cheetah.Auth.External.Google.AttachResponse Attach(global::Games.Cheetah.Auth.External.Google.AttachRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Attach(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Games.Cheetah.Auth.External.Google.AttachResponse Attach(global::Games.Cheetah.Auth.External.Google.AttachRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Attach, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Games.Cheetah.Auth.External.Google.AttachResponse> AttachAsync(global::Games.Cheetah.Auth.External.Google.AttachRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AttachAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Games.Cheetah.Auth.External.Google.AttachResponse> AttachAsync(global::Games.Cheetah.Auth.External.Google.AttachRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Attach, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override GoogleClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new GoogleClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(GoogleBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_RegistryOrLogin, serviceImpl.RegistryOrLogin)
          .AddMethod(__Method_Attach, serviceImpl.Attach).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, GoogleBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_RegistryOrLogin, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Games.Cheetah.Auth.External.Google.RegistryOrLoginRequest, global::Games.Cheetah.Cerberus.Types.Tokens>(serviceImpl.RegistryOrLogin));
      serviceBinder.AddMethod(__Method_Attach, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Games.Cheetah.Auth.External.Google.AttachRequest, global::Games.Cheetah.Auth.External.Google.AttachResponse>(serviceImpl.Attach));
    }

  }
}
#endregion
