// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: matches.matchmaking.external.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Cheetah.Matches.Matchmaking.GRPC {
  public static partial class Matchmaking
  {
    static readonly string __ServiceName = "cheetah.matches.matchmaking.external.Matchmaking";

    static readonly grpc::Marshaller<global::Cheetah.Matches.Matchmaking.GRPC.TicketRequest> __Marshaller_cheetah_matches_matchmaking_external_TicketRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Cheetah.Matches.Matchmaking.GRPC.TicketRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Cheetah.Matches.Matchmaking.GRPC.TicketResponse> __Marshaller_cheetah_matches_matchmaking_external_TicketResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Cheetah.Matches.Matchmaking.GRPC.TicketResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Cheetah.Matches.Matchmaking.GRPC.TicketRequest, global::Cheetah.Matches.Matchmaking.GRPC.TicketResponse> __Method_Matchmaking = new grpc::Method<global::Cheetah.Matches.Matchmaking.GRPC.TicketRequest, global::Cheetah.Matches.Matchmaking.GRPC.TicketResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Matchmaking",
        __Marshaller_cheetah_matches_matchmaking_external_TicketRequest,
        __Marshaller_cheetah_matches_matchmaking_external_TicketResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Cheetah.Matches.Matchmaking.GRPC.MatchesMatchmakingExternalReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Matchmaking</summary>
    [grpc::BindServiceMethod(typeof(Matchmaking), "BindService")]
    public abstract partial class MatchmakingBase
    {
      /// <summary>
      ///*
      ///Создать билет на вход в матч для пользователя
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Cheetah.Matches.Matchmaking.GRPC.TicketResponse> Matchmaking(global::Cheetah.Matches.Matchmaking.GRPC.TicketRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Matchmaking</summary>
    public partial class MatchmakingClient : grpc::ClientBase<MatchmakingClient>
    {
      /// <summary>Creates a new client for Matchmaking</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public MatchmakingClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Matchmaking that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public MatchmakingClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected MatchmakingClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected MatchmakingClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      ///*
      ///Создать билет на вход в матч для пользователя
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Cheetah.Matches.Matchmaking.GRPC.TicketResponse Matchmaking(global::Cheetah.Matches.Matchmaking.GRPC.TicketRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Matchmaking(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///*
      ///Создать билет на вход в матч для пользователя
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Cheetah.Matches.Matchmaking.GRPC.TicketResponse Matchmaking(global::Cheetah.Matches.Matchmaking.GRPC.TicketRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Matchmaking, null, options, request);
      }
      /// <summary>
      ///*
      ///Создать билет на вход в матч для пользователя
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Cheetah.Matches.Matchmaking.GRPC.TicketResponse> MatchmakingAsync(global::Cheetah.Matches.Matchmaking.GRPC.TicketRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return MatchmakingAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///*
      ///Создать билет на вход в матч для пользователя
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Cheetah.Matches.Matchmaking.GRPC.TicketResponse> MatchmakingAsync(global::Cheetah.Matches.Matchmaking.GRPC.TicketRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Matchmaking, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override MatchmakingClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new MatchmakingClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(MatchmakingBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Matchmaking, serviceImpl.Matchmaking).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, MatchmakingBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Matchmaking, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Cheetah.Matches.Matchmaking.GRPC.TicketRequest, global::Cheetah.Matches.Matchmaking.GRPC.TicketResponse>(serviceImpl.Matchmaking));
    }

  }
}
#endregion
