name: release docker image
on:
  release:
    types: [ published ]
jobs:
  release-images:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cheetah-game-platform/rust-builder-x86_64-unknown-linux-musl:0.0.4
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            $CARGO_HOME/registry/index/
            $CARGO_HOME/registry/cache/
            $CARGO_HOME/git/db/
            modules/target/
          key: rust-release-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            rust-release-v1-
      - name: Build servers
        run: cd modules/ && RUSTFLAGS="-Ctarget-cpu=haswell -Ctarget-feature=+avx2" cargo build --release --target x86_64-unknown-linux-musl
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Build image
        run: cd modules/ && version=${{ github.event.release.tag_name }} ./package-server-images.sh

