name: Release documentation site
on:
  release:
    types: [ published ]
jobs:
  user-documentation:
    runs-on: ubuntu-latest
    container:
      image: squidfunk/mkdocs-material:8.0.4
    steps:
      - uses: actions/checkout@v2
      - run: cd docs/application/ && mkdocs gh-deploy --force