name: release-helm-charts
on:
  release:
    types: [ published ]
permissions:
  packages: write
env:
  version: ${{ github.event.release.tag_name }}
jobs:
  release-helm-charts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Supply Version
        run: |
          sed -i.bak "s/999.999.999/$version/" $(find . -name Chart.yaml)
          sed -i.bak "s/999.999.999/$version/" $(find . -name values.yaml)
          sed -i.bak "s/IMAGES_VERSION/$version/" $(find . -name values.yaml)
      - name: Copy Platform Services Charts into Platform
        run: |
          charts=$(find modules -name Chart.yaml)
          platform_dir=hosting/charts/Platform
          for ch in $charts; do
            name=$(echo $ch \
              | sed 's/^modules\///' \
              | sed 's/\/chart\/Chart.yaml$//' \
              | tr [:upper:] [:lower:] | tr / -
            )
            cp -r $ch $platform_dir/$name
          done
      - name: Publish
        run: |
          helm version

          helm dependency update .
          helm package .

          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login https://ghcr.io -u $ --password-stdin
          cat ~/.config/helm/registry/config.json

          repo=oci://ghcr.io/${{ github.repository_owner }} 
          echo "Pushing to $repo..."
          helm push platform-$version.tgz $repo
        working-directory: hosting/charts/Platform
