name: release.images
on:
  release:
    types: [ published ]
jobs:
  build-docker-images:
    uses: ./.github/workflows/templates.build.docker-images.yml
    with:
      version: ${{ github.event.release.tag_name }}
