name: build-on-windows
on:
  workflow_call:
env:
  REALTIME_CLIENT_MANIFEST_PATH: modules/matches/Realtime/client/rust/Realtime/Cargo.toml
  REALTIME_EMBEDDED_MANIFEST_PATH: modules/matches/Realtime/client/rust/Embedded/Cargo.toml
  REALTIME_UDS_MANIFEST_PATH: modules/matches/Realtime/client/rust/UDS/Cargo.toml
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Client
        run: |
          cargo build --manifest-path $REALTIME_CLIENT_MANIFEST_PATH --release
          cargo build --manifest-path $REALTIME_EMBEDDED_MANIFEST_PATH --release
          cargo build --manifest-path $REALTIME_UDS_MANIFEST_PATH --release
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-macos
          path: |
            modules/target/release/*.dylib
            
