name: build-docker-images
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/avkviring/rust-builder-x86_64-unknown-linux-musl:0.0.8
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            $CARGO_HOME/registry/index/
            $CARGO_HOME/registry/cache/
            $CARGO_HOME/git/db/
            rust/target/
          key: rust-release-v2-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            rust-release-v2-
      - name: Build servers
        run: cd rust/ && RUSTFLAGS="-Ctarget-cpu=haswell -Ctarget-feature=+avx2" cargo build --release --target x86_64-unknown-linux-musl
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Build image
        run: version=${{inputs.version}} scripts/package-server-images.sh

