name: build-on-windows
on:
  workflow_call:
env:
  REALTIME_CLIENT_MANIFEST_PATH: rust/Client/Cargo.toml
  REALTIME_EMBEDDED_MANIFEST_PATH: rust/Embedded/Cargo.toml
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Client
        run: |
          rustup target add aarch64-apple-darwin
          cargo build --manifest-path $REALTIME_CLIENT_MANIFEST_PATH --release --target x86_64-apple-darwin
          cargo build --manifest-path $REALTIME_EMBEDDED_MANIFEST_PATH --release --target x86_64-apple-darwin
          cargo build --manifest-path $REALTIME_CLIENT_MANIFEST_PATH --release --target aarch64-apple-darwin
          cargo build --manifest-path $REALTIME_EMBEDDED_MANIFEST_PATH --release --target aarch64-apple-darwin
          lipo -create -output rust/target/release/libcheetah_client.dylib rust/target/aarch64-apple-darwin/release/libcheetah_client.dylib  rust/target/x86_64-apple-darwin/release/libcheetah_client.dylib
          lipo -create -output rust/target/release/libcheetah_embedded.dylib rust/target/aarch64-apple-darwin/release/libcheetah_embedded.dylib  rust/target/x86_64-apple-darwin/release/libcheetah_embedded.dylib
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-macos
          path: |
            rust/target/release/*.dylib
            
