name: test.cargo-fmt
on:
  pull_request:
    types:
      - synchronize
      - opened
jobs:
  test-cargo-fmt:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/avkviring/rust-builder-x86_64-unknown-linux-musl:1.75.0_1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            $CARGO_HOME/registry/index/
            $CARGO_HOME/registry/cache/
            $CARGO_HOME/git/db/
            rust/target/
          key: rust-fmt-v1-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            rust-fmt-v1-
      - name: Lint cargo fmt
        run: cd rust/ && cargo fmt --all -- --check

