name: test.cargo-udeps
on:
  pull_request:
    types:
      - synchronize
      - opened
jobs:
  test-cargo-udeps:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/avkviring/rust-builder-x86_64-unknown-linux-musl:1.75.0_1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            $CARGO_HOME/cargo/registry/index/
            $CARGO_HOME/cargo/registry/cache/
            $CARGO_HOME/cargo/git/db/
            rust/target/
          key: rust-udeps-v1-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            rust-udeps-v1-
      - name: Lint udeps
        run: cd rust/ && cargo +nightly udeps


