#
# Тестируем сборки под разные платформы
#
name: test.unity.build
on:
  pull_request:
    types:
      - synchronize
      - opened
jobs:
  test-build-unity-client:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneLinux64
          - iOS
          - Android
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.7
        with:
          path: |
            client/Unity/Library
          key: test-build-${{ matrix.targetPlatform }}-unity-client-${{ github.sha }}
          restore-keys: |
            test-build-${{ matrix.targetPlatform }}-unity-client-
      - name: Generate GRPC Implementations
        run: cd scripts && ./generate-all.sh
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: client/Unity/
          targetPlatform: ${{ matrix.targetPlatform }}


