#
# Интеграционный тест
#
name: test.integration
on:
  pull_request:
    types:
      - synchronize
      - opened
jobs:
  build-docker-images:
    uses: ./.github/workflows/templates.build.docker-images.yml
    with:
      version: 999.999.999
  build-on-linux:
    uses: ./.github/workflows/templates.build-on-linux.yml
  build-on-windows:
    uses: ./.github/workflows/templates.build-on-windows.yml
  e2e-integration-unity-docker-test:
    runs-on: ubuntu-latest
    needs:
      - build-docker-images
      - build-on-linux
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.7
        with:
          path: |
            e2e/Unity/Library
          key: integration-docker-test-${{ github.sha }}
          restore-keys: |
            integration-docker-test-
      - uses: actions/download-artifact@v2
        with:
          name: build-on-linux-result
          path: build-on-linux-result
      - name: Copy Libraries
        run: |
          lib_path=modules/matches/Realtime/client/Unity/games.cheetah.matches.realtime/Runtime/Library                    
          cp build-on-linux-result/libcheetah_matches_realtime_client.so $lib_path/linux.so
          lib_path=modules/matches/Realtime/client/Unity/games.cheetah.matches.realtime.embedded-server/Runtime/FFI/Library/          
          cp build-on-linux-result/libcheetah_matches_realtime_embedded.so $lib_path/
      - name: Generate GRPC Implementations
        run: scripts/generators/grpc/unity.sh
      - name: Configure integration-test-config.json
        run: echo '{"ServerImageVersion":"999.999.999"}' > e2e/Unity/integration-test-config.json
      - uses: cheetah-game-platform/unity-test-runner@main
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: e2e/Unity/
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: All
          useHostNetwork: true
  run-servers-on-kubernetes:
    runs-on: ubuntu-latest
    needs:
      - build-docker-images
    container: ghcr.io/cheetah-game-platform/kubernetes-control-image:1.2.3
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd e2e/Unity/Server/Helmwave/
          echo '${{ secrets.KUBERNETES_STAGE_CLUSTER }}' >> /tmp/kubeconfig.xml
          export KUBECONFIG=/tmp/kubeconfig.xml
          helm plugin list
          helmwave down --build || echo 
          ./install.sh
  e2e-integration-unity-on-linux-kubernetes-test:
    runs-on: ubuntu-latest
    needs:
      - run-servers-on-kubernetes
      - build-on-linux
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.7
        with:
          path: |
            e2e/Unity/Library
          key: integration-docker-test-${{ github.sha }}
          restore-keys: |
            integration-docker-test-
      - uses: actions/download-artifact@v2
        with:
          name: build-on-linux-result
          path: build-on-linux-result
      - name: Copy Libraries
        run: |
          lib_path=modules/matches/Realtime/client/Unity/games.cheetah.matches.realtime/Runtime/Library                    
          cp build-on-linux-result/libcheetah_matches_realtime_client.so $lib_path/linux.so
          lib_path=modules/matches/Realtime/client/Unity/games.cheetah.matches.realtime.embedded-server/Runtime/FFI/Library/          
          cp build-on-linux-result/libcheetah_matches_realtime_embedded.so $lib_path/
      - name: Generate GRPC Implementations
        run: scripts/generators/grpc/unity.sh
      - name: Configure integration-test-config.json
        run: echo "{\"ServerHost\":\"stage1.stage-a.cheetah.games\"}" >  e2e/Unity/integration-test-config.json
      - uses: cheetah-game-platform/unity-test-runner@main
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: e2e/Unity/
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: All
          useHostNetwork: true
