#
# Интеграционный тест
#
name: test.integration.docker
on:
  pull_request:
    types:
      - synchronize
      - opened
jobs:
  build-docker-images:
    uses: ./.github/workflows/templates.build.docker-images.yml
    with:
      version: 999.999.998
  build-realtime-client-so:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cheetah-game-platform/rust-builder-x86_64-unknown-linux-gnu-old-glib:0.0.5
    steps:
      - uses: actions/checkout@v3
      - name: Build Client
        run: |
          cargo build --manifest-path modules/matches/Realtime/client/Rust/Cargo.toml --release
          mv modules/target/release/libcheetah_matches_realtime_client.so modules/target/release/linux.so
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux.so
          path: |
            modules/target/release/linux.so
  e2e-integration-unity-docker-test:
    runs-on: ubuntu-latest
    needs:
      - build-docker-images
      - build-realtime-client-so
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.7
        with:
          path: |
            e2e/Unity/Library
          key: integration-docker-test-${{ github.sha }}
          restore-keys: |
            integration-docker-test-
      - uses: actions/download-artifact@v2
        with:
          name: linux.so
          path: modules/matches/Realtime/client/Unity/games.cheetah.matches.realtime/Runtime/Library/
      - name: Generate GRPC Implementations
        run: scripts/generators/grpc/unity.sh
      - name: Configure integration-test-config.json
        run: echo '{"ServerImageVersion":"999.999.998"}' > e2e/Unity/integration-test-config.json
      - uses: cheetah-game-platform/unity-test-runner@main
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: e2e/Unity/
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: All
          useHostNetwork: true

