#
# Интеграционный тест
#
name: test.integration.docker
on:
  pull_request:
    types:
      - synchronize
      - opened
jobs:
  build-docker-images:
    uses: ./.github/workflows/templates.build.docker-images.yml
    with:
      version: 999.999.998
  build-realtime-client-library-linux:
    uses: ./.github/workflows/templates.build.realtime-client-library-linux.yml
  e2e-integration-unity-docker-test:
    runs-on: ubuntu-latest
    needs:
      - build-docker-images
      - build-realtime-client-library-linux
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.7
        with:
          path: |
            e2e/Unity/Library
          key: integration-docker-test-${{ github.sha }}
          restore-keys: |
            integration-docker-test-
      - uses: actions/download-artifact@v2
        with:
          name: realtime-client-library-linux
          path: modules/matches/Realtime/client/Unity/games.cheetah.matches.realtime/Runtime/Library/
      - name: Generate GRPC Implementations
        run: scripts/generators/grpc/unity.sh
      - name: Configure integration-test-config.json
        run: echo '{"ServerImageVersion":"999.999.998"}' > e2e/Unity/integration-test-config.json
      - uses: cheetah-game-platform/unity-test-runner@main
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: e2e/Unity/
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: All
          useHostNetwork: true

